### ISSUE TITLE
Main Menu TODO

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/Unilateralis#1]
Complete Main Menu GUI:

- [ ] Main Menu GUI Layout
- [ ] Code Framework to interact with following scenes
- [ ] Options Dialog
- [ ] Save/Load Framework
- [ ] In-App Purchase Store Framework
