### ISSUE TITLE
Options Dialog TODO

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/Unilateralis#3]
- [ ] Volume Mixer Slider Code
- [ ] GFX Settings Code
- [ ] Submit Changes Code
- [ ] Cancel/Close Code

**Comment by jasonjoyce971** [comment]
Data manager as script object causes issues with data transfer.

Convert to game object and reference script instance instead.
